import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "./components/SideBar";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <div className="flex w-screen">
          <SideBar /> 
          <div className="flex flex-col w-full bg-gray-100">
            <Header />
            <main className="px-6 py-5">
              {children}
            </main>
          </div>
        </div>  
      </body>
    </html>
  );
}
